name: StoragePeek
version: '${project.version}'
main: fr.skynex.storagepeek.StoragePeek
api-version: '1.20'
folia-supported: true
author: Skynex
description: A premium 3D container peeking plugin using ItemDisplays.
softdepend: [Oraxen, Nexo, ItemsAdder, WorldGuard, Lands, GriefPrevention, BentoBox, SuperiorSkyblock2, Towny, LWC, Residence, CraftEngine, CombatLogX, CombatTagPlus, PvPManager, DeluxeCombat, GriefDefender, PlotSquared]
commands:
  storagepeek:
    description: Main command for StoragePeek.
    aliases: [sp, peek]
